### ISSUE TITLE
Sleeping with "setter" config doesn't reset rain

### ISSUE THREAD

**Issue by piwaku** [Nuytemans-Dieter/BetterSleeping#154] opened 2020-07-27 13:47 UTC
**Describe the bug**
Sleeping at night while raining does not reset weather to clear. 

**To Reproduce**
1. /time set night
2. /weather storm
3. Sleep in a bed
4. Rain remains

**Expected behavior**
Vanilla behavior that rain should stop after sleeping for the night per the wiki: https://minecraft.gamepedia.com/Bed#Passing_the_night

Code is different between timesetter and timesmooth. Timesetter should have "if (world.isThundering() **|| world.hasStorm()**)" to match vanilla behavior, line 41. Reference timesmooth line 30 has correct check to end weather effects if sleeping and if storming _OR_ raining.

**Comment by piwaku** [comment] 2020-07-27 14:55
For reference, this is version 3.0.1. I see this was addressed in 3.0.0 with #147 . I'm not sure which version is latest now as 3.0.1 shows many commits behind.

**Comment by Nuytemans-Dieter** [comment] 2020-07-27 15:05
Thank you for reporting this issue. The naming of the master branch wasn't chosen well (v3.0.0) while in fact it's v3's latest code. So sorry for the confusion.

You are correct, this is a duplicate of #143. And the fix will be included in the next release (3.0.2).

**Closed** 2020-07-27 17:47 UTC
Labels: Potential bug
